services:
  postgres:
    image: postgres:17-alpine
    container_name: minea-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: minea
      POSTGRES_USER: minea
      POSTGRES_PASSWORD: minea

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: